name: Build and Deploy (production)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SITE_NAME: "Safetag"

    steps:
      # Cancel previous workflows to avoid overlapping deploys as content
      # editing might add several commits in short intervals.
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo pip install transifex-client

      - name: Set up secrets
        run: |
          touch .env
          echo TRANSIFEX_USER=${{ secrets.TRANSIFEX_USER }} >> .env
          echo TRANSIFEX_PASSWORD=${{ secrets.TRANSIFEX_PASSWORD }} >> .env
          cp .env .env.production
          cp .env .env.development
          cat .env

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install and lint
        run: |
          yarn install
          yarn lint

      - name: Update translations from Transifex
        run: |
          echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"${{ secrets.TRANSIFEX_USER }}"$'\npassword = '"${{ secrets.TRANSIFEX_PASSWORD }}"$'\ntoken = '"${{ secrets.TRANSIFEX_TOKEN }}"$'\n' | tee ~/.transifexrc
          yarn extract
          yarn transifex-push
          yarn transifex-pull
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: guide
          FOLDER: public
          CLEAN: true # Automatically remove deleted files from the deploy branch
